### ISSUE TITLE
babel, matlab, cpp have different interpretation of same function

### ISSUE THREAD

**Issue by Groostav** [EmpowerOperations/babel#10]
TBD

From Cenk:

```
inputs:
  x1: {lower: -1.0, upper: 1.0}
  x2: {lower: -1.0, upper: 1.0}
objectives:
  f1: "-2.0*2.718281828459045^(15.0*(-(x1-0.1)^2-x2^2.0))-2.718281828459045^(20.0*(-(x1-0.6)^2.0-(x2-0.6)^2.0))+2.718281828459045^(20.0*(-(x1+0.6)^2.0-(x2-0.6)^2.0))+2.718281828459045^(20*(-(x1-0.6)^2.0-(x2+0.6)^2))+2.718281828459045^(20*(-(x1+0.6)^2.0-(x2+0.6)^2.0))"
  f2: "2.0*2.718281828459045^(20.0*(-x1^2.0-x2^2.0))+2.718281828459045^(20.0*(-(x1-0.4)^2.0-(x2-0.6)^2.0))-2.718281828459045^(20.0*(-(x1+0.5)^2.0-(x2-0.7)^2.0))-2.718281828459045^(20.0*(-(x1-0.5)^2.0-(x2+0.7)^2.0))+2.718281828459045^(20.0*(-(x1+0.4)^2.0-(x2+0.8)^2.0))"
```

from george:

>I may have discovered a bug in Babel. I persistently get crashing when running OASIS with the Behzad problem but don't get the problem in my C++ implementation of the problem. I noticed a huge difference in the objective values I was getting between the two implementations, but can't find anything wrong with my implementation. I copied the functions into MATLAB and plugged in x1 = x2 = 1.0, and I got the following values:
>
>f1 = -0.0017 f2 = 3.0432e-05
>however in OASIS I get huge values
>I get 7E20 and -5.77E18
>for the two functions
>now, regardless, this has revealed a problem in my algorithm code, however I do think there's a problem with how Babel is interpreting the functions
